[context.production]
  command = "echo 'skipping'"

[build]
  publish = "_site/"
  command = "jekyll build --trace --limit-posts 10 --baseurl ''"

[build.environment]
  RUBY_VERSION = "2.6"

[build.processing]
  skip_processing = true