[build]
  publish = "_site/"
  command = "jekyll build --trace --limit-posts 10"

[build.environment]
  RUBY_VERSION = "2.6"

[context.deploy-preview]
  publish = "_site/"
  command = "jekyll build --trace --limit-posts 10"