name: gh-actions/site

on: [push, pull_request]

jobs:
  build:
    runs-on: ubuntu-18.04
    name: Deploy netlify
    steps:
    - uses: actions/checkout@master
    - uses: actions/setup-ruby@v1
      with:
        ruby-version: 2.6
    - name: install bundler
      run: gem install bundler:1.17.3
    - name: bundle install
      run: bundle install --jobs 4 --retry 3
    - name: build site
      run: bundle exec jekyll build --limit-posts 1 --baseurl ''

    # deploy to netlify using CLI
    - uses: netlify/actions/cli@master
      with:
        args: deploy --dir=site
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        NETLIFY_AUTH_TOKEN: ${{ secrets.NETLIFY_AUTH_TOKEN }}
        NETLIFY_SITE_ID: ${{ secrets.NETLIFY_SITE_ID }}
